apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://F53840BD682AF77A7D694BA0B90D9BB4.gr7.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:203545398842:cluster/production-apac
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://CFBA091A884DF0DCD4354E8E58FEBDC8.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:203545398842:cluster/production
contexts:
- context:
    cluster: arn:aws:eks:ap-south-1:203545398842:cluster/production-apac
    user: arn:aws:eks:ap-south-1:203545398842:cluster/production-apac
  name: arn:aws:eks:ap-south-1:203545398842:cluster/production-apac
- context:
    cluster: arn:aws:eks:us-east-1:203545398842:cluster/production
    user: arn:aws:eks:us-east-1:203545398842:cluster/production
  name: arn:aws:eks:us-east-1:203545398842:cluster/production
current-context: arn:aws:eks:us-east-1:203545398842:cluster/production
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-south-1:203545398842:cluster/production-apac
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - production-apac
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:us-east-1:203545398842:cluster/production
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - production
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
